export const SHARE_CHARTS = [
  {
    slug: "shiller-cape",
    anchorId: "metric-cape",
    tabPath: "/equity-valuation",
    title: "Shiller CAPE Ratio",
    subtitle: "Cyclically adjusted S&P 500 valuation",
    category: "Equity Valuation",
    stat: "37.5",
    comparison: "vs 17.4 long-run average",
    signal: "red",
    description: "CAPE remains historically stretched, though today's rate regime and business mix complicate direct comparison.",
    points: [5, 32.6, 5.6, 12, 24.1, 6.6, 17, 23, 44.2, 22, 27.5, 13.3, 26, 31, 28, 36, 37.5],
  },
  {
    slug: "nasdaq-forward-pe",
    anchorId: "metric-nasdaq-forward-pe",
    tabPath: "/equity-valuation",
    title: "Nasdaq-100 Forward P/E",
    subtitle: "Forward P/E vs trailing 10-year average",
    category: "Equity Valuation",
    stat: "21.0x",
    comparison: "vs 23.3x trailing 10Y average",
    signal: "green",
    description: "The Nasdaq-100 forward P/E sits below its trailing 10-year average, a constructive AI-leadership valuation check.",
    points: [17.4, 19.2, 20.1, 21.4, 20.6, 18.0, 22.6, 33.9, 28.1, 27.0, 20.2, 24.2, 25.8, 23.0, 26.4, 21.0],
  },
  {
    slug: "forward-pe",
    anchorId: "metric-forward-pe",
    tabPath: "/equity-valuation",
    title: "Forward P/E",
    subtitle: "S&P 500 price vs next-12-month expected earnings",
    category: "Equity Valuation",
    stat: "21.8x",
    comparison: "vs 16.7x average",
    signal: "yellow",
    description: "Forward multiples are elevated, but still below the dot-com peak and supported by strong earnings growth.",
    points: [14.5, 25.5, 26, 16, 15.2, 10.5, 15, 22, 17, 21, 21.8],
  },
  {
    slug: "buffett-indicator",
    anchorId: "metric-buffett",
    tabPath: "/equity-valuation",
    title: "Buffett Indicator",
    subtitle: "US market capitalization vs US GDP",
    category: "Equity Valuation",
    stat: "230%",
    comparison: "vs 90% long-run average",
    signal: "red",
    description: "Market cap relative to GDP remains one of the clearest traditional valuation warning lights.",
    points: [75, 33, 58, 92, 148, 80, 110, 60, 120, 170, 200, 220, 230],
  },
  {
    slug: "equity-risk-premium",
    anchorId: "metric-erp",
    tabPath: "/equity-valuation",
    title: "Equity Risk Premium",
    subtitle: "Forward earnings yield minus 10Y Treasury yield",
    category: "Equity Valuation",
    stat: "0.3%",
    comparison: "vs 4.0% average",
    signal: "red",
    description: "Investors are being paid very little extra return for equity risk, even though the premium is still positive.",
    points: [4, 0.5, -0.5, 3.5, 8, 4, 4.5, 2.5, 0.3],
  },
  {
    slug: "top-10-concentration",
    anchorId: "metric-top-10-concentration",
    tabPath: "/market-structure",
    title: "Top 10 Concentration",
    subtitle: "Largest 10 S&P 500 members as index weight",
    category: "Market Structure",
    stat: "37.2%",
    comparison: "vs 27% dot-com peak",
    signal: "red",
    description: "The index is historically concentrated, but the largest firms also carry unusually high earnings power.",
    points: [16, 17, 27, 19, 20, 19, 28, 37, 41, 37.2],
  },
  {
    slug: "margin-debt-market-cap",
    anchorId: "metric-margin-debt-market-cap",
    tabPath: "/market-structure",
    title: "Margin Debt / Market Cap",
    subtitle: "Borrowed money normalized by total market size",
    category: "Market Structure",
    stat: "1.68%",
    comparison: "below 2000 and 2008",
    signal: "green",
    description: "Leverage looks far less extreme once margin debt is scaled against the size of the market.",
    points: [1.2, 2.5, 1.4, 2.7, 1.1, 1.7, 2.1, 1.5, 1.68],
  },
  {
    slug: "capex-gdp",
    anchorId: "metric-capex-gdp",
    tabPath: "/market-structure",
    title: "Capex / GDP",
    subtitle: "Private nonresidential investment as share of GDP",
    category: "Market Structure",
    stat: "13.9%",
    comparison: "vs 14.6% dot-com peak",
    signal: "yellow",
    description: "AI capex is lifting investment intensity toward dot-com-era levels, but it has not yet broken through them.",
    points: [11.8, 13.2, 14.6, 12.4, 13.1, 11.6, 13.0, 13.6, 13.9],
  },
  {
    slug: "capex-operating-cash-flow",
    anchorId: "metric-capex-operating-cash-flow",
    tabPath: "/market-structure",
    title: "Capex / Operating Cash Flow",
    subtitle: "Corporate investment relative to internally generated cash",
    category: "Market Structure",
    stat: "111%",
    comparison: "vs 120% average",
    signal: "green",
    description: "Capex intensity remains below its long-run average on this broad FRED proxy.",
    points: [108, 142, 125, 135, 96, 110, 118, 116, 111],
  },
  {
    slug: "yield-curve",
    anchorId: "metric-yield-curve",
    tabPath: "/credit-debt",
    title: "Yield Curve",
    subtitle: "10Y Treasury yield minus 2Y Treasury yield",
    category: "Credit & Debt",
    stat: "+52bp",
    comparison: "positively sloped again",
    signal: "green",
    description: "The curve has re-steepened after the 2022-24 inversion, a healthier setup than prior recession warnings.",
    points: [1.0, -0.5, 2.5, -0.2, 2.8, 1.5, -1.0, 0.52],
  },
  {
    slug: "hy-credit-spread",
    anchorId: "metric-hy-credit-spread",
    tabPath: "/credit-debt",
    title: "HY Credit Spread",
    subtitle: "High-yield bond spread over Treasuries",
    category: "Credit & Debt",
    stat: "3.3%",
    comparison: "vs 4.9% average",
    signal: "yellow",
    description: "Credit spreads are calm and below average, useful but worth watching for complacency.",
    points: [4.5, 8.0, 5.2, 21.8, 6.0, 3.6, 5.8, 3.3],
  },
  {
    slug: "household-debt-income",
    anchorId: "metric-household-debt-income",
    tabPath: "/credit-debt",
    title: "Household Debt / Income",
    subtitle: "Household debt relative to disposable income",
    category: "Credit & Debt",
    stat: "93%",
    comparison: "vs 133% in 2008",
    signal: "green",
    description: "Household leverage remains far healthier than the 2008 credit bubble setup.",
    points: [80, 97, 112, 133, 118, 103, 96, 93],
  },
  {
    slug: "eps-growth",
    anchorId: "metric-eps-growth",
    tabPath: "/macro",
    title: "S&P 500 EPS Growth",
    subtitle: "Estimated year-over-year earnings growth",
    category: "Macro",
    stat: "+15.2%",
    comparison: "vs +8% average",
    signal: "green",
    description: "Earnings growth is materially better than the profit deterioration seen around prior major bubbles.",
    points: [12, -2, 8, -30, 22, 5, 10, 15.2],
  },
  {
    slug: "real-gdp-growth",
    anchorId: "metric-real-gdp-growth",
    tabPath: "/macro",
    title: "Real GDP Growth",
    subtitle: "Inflation-adjusted US economic growth",
    category: "Macro",
    stat: "2.0%",
    comparison: "near trend",
    signal: "green",
    description: "The real economy is still expanding, unlike the contractionary setup around 2008.",
    points: [4.0, 1.0, 3.5, -4.3, 2.7, 2.2, 2.5, 2.0],
  },
  {
    slug: "fed-funds-rate",
    anchorId: "metric-fed-funds-rate",
    tabPath: "/monetary-policy",
    title: "Fed Funds Rate",
    subtitle: "Effective federal funds rate",
    category: "Monetary Policy",
    stat: "3.6%",
    comparison: "near long-run average",
    signal: "green",
    description: "Policy is restrictive versus the post-GFC era but below the tightening peaks before 2000 and 2008.",
    points: [5.5, 6.5, 1.0, 5.25, 0.1, 2.4, 5.3, 3.6],
  },
  {
    slug: "m2-money-supply",
    anchorId: "metric-m2-money-supply",
    tabPath: "/monetary-policy",
    title: "M2 Money Supply",
    subtitle: "Money supply, scored against GDP",
    category: "Monetary Policy",
    stat: "$22.4T",
    comparison: "liquidity base still full",
    signal: "yellow",
    description: "The money stock remains large after the COVID-era expansion, though the scored ratio has cooled from its peak.",
    points: [4.9, 6.3, 8.0, 10.5, 13.5, 19.0, 21.7, 22.4],
  },
  {
    slug: "fed-balance-sheet",
    anchorId: "metric-fed-balance-sheet",
    tabPath: "/monetary-policy",
    title: "Fed Balance Sheet",
    subtitle: "Federal Reserve assets, scored against GDP",
    category: "Monetary Policy",
    stat: "$6.7T",
    comparison: "below 2022 peak",
    signal: "yellow",
    description: "The Fed balance sheet is shrinking but remains far larger than pre-2008 norms.",
    points: [0.6, 0.9, 2.2, 4.5, 7.4, 8.8, 7.6, 6.7],
  },
  {
    slug: "vix",
    anchorId: "metric-vix",
    tabPath: "/sentiment",
    title: "VIX",
    subtitle: "S&P 500 implied volatility",
    category: "Sentiment",
    stat: "24.1",
    comparison: "not euphorically calm",
    signal: "yellow",
    description: "Volatility is not at the complacent lows that typically mark late-cycle euphoria.",
    points: [19, 33, 18, 80, 16, 12, 28, 24.1],
  },
  {
    slug: "case-shiller-hpi",
    anchorId: "metric-case-shiller",
    tabPath: "/housing",
    title: "Case-Shiller HPI",
    subtitle: "US national home price index",
    category: "Housing",
    stat: "332.0",
    comparison: "supply-driven, not 2006-style credit",
    signal: "yellow",
    description: "Housing is expensive, but today's setup is driven more by shortage than reckless lending.",
    points: [100, 125, 190, 140, 160, 210, 290, 332],
  },
  {
    slug: "global-debt-gdp",
    anchorId: "metric-global-debt-gdp",
    tabPath: "/global-risk",
    title: "Global Debt / GDP",
    subtitle: "BIS proxy for global leverage",
    category: "Global Risk",
    stat: "246.3%",
    comparison: "above average, below pandemic peak",
    signal: "yellow",
    description: "Global leverage limits room for policy response when shocks arrive, even if it is not an immediate trigger.",
    points: [190.9, 205, 216.6, 230, 260, 285, 252, 246.3],
  },
];

export const SHARE_CHART_BY_SLUG = Object.fromEntries(SHARE_CHARTS.map((chart) => [chart.slug, chart]));
export const SHARE_CHART_BY_ANCHOR = Object.fromEntries(SHARE_CHARTS.map((chart) => [chart.anchorId, chart]));

export const getShareChartBySlug = (slug) => SHARE_CHART_BY_SLUG[slug] || null;
export const getShareChartByAnchorId = (anchorId) => SHARE_CHART_BY_ANCHOR[anchorId] || null;
